-------------------------------------------------------------------------------
Test set: org.tudelft.ewi.ceng.examples.vectorOps.VectorOpsMainTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in org.tudelft.ewi.ceng.examples.vectorOps.VectorOpsMainTest
vectorOpsTest(org.tudelft.ewi.ceng.examples.vectorOps.VectorOpsMainTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: Directory resources/JNI_UTILS_TEST already exists
	at org.junit.Assert.fail(Assert.java:88)
	at org.tudelft.ewi.ceng.TestUtils.initTestDir(TestUtils.java:32)
	at org.tudelft.ewi.ceng.examples.vectorOps.VectorOpsMainTest.init(VectorOpsMainTest.java:26)

